services:
  postgres:
    container_name: postgres_code_library
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: code_library_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: